
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM JOBS;

-- 특정 컬럼만 조회
-- 문자와 날짜는 왼쪽에, 숫자는 오른쪽에 표시
SELECT FIRST_NAME, HIRE_DATE, EMAIL, SALARY FROM EMPLOYEES;

-- 컬럼명 자리에서는 숫자 또는 날짜가 연산이 됩니다
SELECT FIRST_NAME, SALARY, SALARY + SALARY * 01. FROM EMPLOYEES;

-- PK는 EMPLOYEE_ID, FK - DEPARTMENT-ID NULL
SELECT * FROM EMPLOYEES;

-- 엘리어스(별칭)
SELECT FIRST_NAME AS 별칭, SALARY AS 급여, SALARY + SALARY * 0.1 "최종 급여" FROM EMPLOYEES;

-- 문자열 연결 ||
-- 홑 안에서 홑 쓰고 싶다면 ''
SELECT 'HELLO' || ' WORLD' FROM EMPLOYEES;
SELECT FIRST_NAME || '님의 급여는' || SALARY || '$입니다' FROM EMPLOYEES;

-- DISTINT (중복 제거) 키워드
SELECT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;

-- ROWNUM (조회되 순서) ROWID (레코드가 저장된 위치)
SELECT EMPLOYEE_ID, FIRST_NAME, ROWID, ROWNUM FROM EMPLOYEES;

